name: My first workflow

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Welcome msg
          run: |
            echo "My first Github Actions Job"
            ls -ltra
            cat README.md
        
        - name: Execute 3rd party lib
          run: cowsay -f dragom "Run !!" >> dragon.txt

#        - name: List files
#          run: ls 

#        - name: Read file
#          run: cat README.md 